name: Test CI

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: set envioronment variables
        id: env_var
        run: |
          VERSION=$(echo "v4.0.1" | cut -f2 -d"v")
          echo ::set-output name=NEW_VERSION::$(echo "https://github.com/adobe/aem-site-template-basic/releases/download/$VERSION/aem-site-template-basic-$VERSION.zip")

      # Runs a set of commands using the runners shell
      - name: output variables
        run: |
          echo ${{ steps.env_var.outputs.NEW_VERSION }}
