name: Test CI

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: set envioronment variables
        id: env_var
        run: |
          echo ::set-output name=VERSION::$(echo "v4.0.1")

      # Runs a set of commands using the runners shell
      - name: output variables
        run: |
          echo ${{ steps.env_var.outputs.VERSION }}
